[package]
name = "untitled"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", features = ["vorbis", "wav"] }
bevy_rapier2d = "0.31"
fastrand = "2.3.0"
rand = "0.9"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
