[package]
name = "untitled"
version = "0.1.0"
edition = "2024"

[features]
default = []
debug-physics = []

[dependencies]
bevy = { version = "0.16", features = ["vorbis", "wav"] }
bevy_ecs_tilemap = "0.16"
bevy_rapier2d = "0.31"
fastrand = "2.3.0"
itertools = "0.14"
noise = "0.9"
rand = "0.9"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.8"
rayon = "1.11"
image = "0.25"
mlua = { version = "0.10", features = ["lua54", "vendored"] }
